http:
  listener:
    host: "localhost"
    port: "8081"
    path: "/travelOnTipCall/{serviceType}"
db:
  mysql:
     host: "localhost"
     port:  "3306"
     username: "root"
     password: "96421qwerty#"
     
    
  